[workspace]
authors = ["Ruziboyev97 Ruziboyev <mr.timurchik97@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo-hithub"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.5.0.dev2025061317,<26"
